# -*- coding: utf-8 -*-
"""Model for Hiring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G27whOqL9_gCOV2lqjUW_zxrbz75vF_i
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Project Deployment/hiring.csv')
df

df.info()

df.isnull().sum()

df['test_score'].fillna(df['test_score'].mean(),inplace=True)

df['experience'].fillna(0,inplace=True)

def string_to_num(word):
  dict = {'zero':0, 'one':1,'two':2,'three':3, 'four':4, 'five':5, 'six':6, 'seven':7, 'eight':8, 'nine':9, 'ten':10, 'eleven':11, 'twelve':12 ,0:0}                         
  return dict[word]

df['experience'] = df['experience'].apply(lambda x: string_to_num(x))
df

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x = df.iloc[ : ,: 3]
y = df.iloc[ : , -1]

x

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.1, random_state =5)

model = LinearRegression()

model.fit(x_train,y_train)

y_pred = model.predict(x_test)
y_pred

y_pred = model.predict([[5,8,7]])
y_pred

import pickle
pickle.dump(model,open("model.pkl","wb"))

